---
# tasks file for master_setup
  - name: checking if kubelet is running or not
    service:
      name: kubelet
      state: started
    register: kubelet_running

  - name: executing kubeadm init command
    command: 'kubeadm init'
    loop: "{{ groups['master-node'] }}"
    ignore_errors: true 

  - name: creating .kube folder
    file:
      path: /root/.kube
      state: directory
    register: kube_dir_created
  
  - name: creating kube config file
    block:
    - name: copy config file to .kube folder
      copy:
        src: /etc/kubernetes/kubelet.conf
        dest: $HOME/.kube/config
        mode: 777
        remote_src: yes

    - name: saving the token 
      shell: "kubeadm token create --print-join-command > /join_command.sh"

    - name: fetch the token command
      fetch:
       src: /join_command.sh
       dest: /opt/seagate/halo/install_depot/k8s/setup_playbook/worker_setup/files/
       flat: yes

    - name: installing calico
      shell: kubectl apply -f /opt/seagate/halo/install_depot/k8s/calico-etcd.yaml
    when: kube_dir_created.changed
