# Network configuration inputs 
interfaces:
    # Static network IP configutation
    <INTERFACE_DEVICE_NAME>:
        interface_type: Ethernet
        bootproto: none
        interface: <INTERFACE_DEVICE_NAME>
        ip_addr: <IPV4_ADDRESS>
        subnet: <NETMASK>
        gateway: <GATEWAY_ADDRESS>
    # Dynamic network IP configutation
    <INTERFACE_DEVICE_NAME>:
        interface_type: Ethernet
        bootproto: dhcp
        interface: <INTERFACE_DEVICE_NAME>

