# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates

# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# For any questions about this software or licensing, please email
# opensource@seagate.com or cortx-questions@seagate.com.

# Network configuration inputs 
network:
    interfaces:
        # Static network IP configutation
        <INTERFACE_DEVICE_NAME1>:
            interface_type: Ethernet
            bootproto: none
            interface: <INTERFACE_DEVICE_NAME1>
            ip_addr: <IPV4_ADDRESS>
            subnet: <NETMASK>
            gateway: <GATEWAY_ADDRESS>
        # Dynamic network IP configutation
        <INTERFACE_DEVICE_NAME2>:
            interface_type: Ethernet
            bootproto: dhcp
            interface: <INTERFACE_DEVICE_NAME2>

# Cluster configuration inputs 
k8s:
    all:
        hosts:
        children:
            master-node:
                hosts:
                    ssc-vm-g2-rhev4-3414.colo.seagate.com:
            worker-node:
                hosts:
                    ssc-vm-g2-rhev4-3412.colo.seagate.com:
