---
# tasks file for worker_setup

  - name: copy the join command file
    copy:
      src: join_command.sh
      dest: /root/join_command1.sh
      mode: "u+rwx"
    register: join_command_copied

  - name: running kubeadm join command
    shell: "/root/join_command1.sh"
    when: join_command_copied.changed 

  - name: creating kube config file
    block:   
    - name: creating .kube folder
      file:
        path: /root/.kube
        state: directory

    - name: copy config file to .kube folder
      copy:
        src: /etc/kubernetes/kubelet.conf
        dest: $HOME/.kube/config
        mode: 777
        remote_src: yes
